services:
  - type: web
    name: car-recommender
    runtime: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: development
    plan: free